version: '3.8'
services:
  db:
    image: pgvector/pgvector:pg16
    container_name: chatbot_db
    environment:
      - POSTGRES_USER=lazymodthai
      - POSTGRES_PASSWORD=chatbot1234
      - POSTGRES_DB=chatbot_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: chatbot_pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - db
    restart: unless-stopped

volumes:
  postgres_data: